osx_instance:
  image: mojave-xcode-10.1

task:
  name: Install GHC
  script: brew install python@3
  script: curl -sL https://haskell.futurice.com/haskell-on-macos.py | python3 - --make-dirs --paths.d --ghc-alias=8.4.4 --cabal-alias=2.4.1.0 install ghc-8.4.4 cabal-install-2.4.1.0
  script: cabal --version
